aws:
  region: ap-southeast-4
appCert:
  domainName: example.net
  ssmParameterName: /certs/webapp/example.net
  subjectAlternativeNames:
    - '*.example.net'
    - soso.info
    - www.soso.info
    - anan.link
    - www.anan.link
    - clcl.link
    - www.clcl.link
zoneS3Cloudfront:
  - zoneName: example.net
    bucket: example.net
    alias:
      - www
  - zoneName: soso.info
    bucket: soso.info
    alias:
      - www
  - zoneName: anan.link
    bucket: anan.link
    alias:
      - www
  - zoneName: clcl.link
    bucket: clcl.link
    alias:
      - www
